name = input("შენი სახელი: ")
surname = input("შენი გვარი: ")
momname = input("დედის სახელი: ")
momsurname = input("დედის გვარი: ")
dadname = input("მამის სახელი: ")
dadsurname = input("მამის გვარი: ")
color = input("საყვარელი ფერი: ")
car = input("საყვარელი მანქანა: ")
hobby1 = input("შენი პირველი საყვარელი ჰობი: ")
hobby2 = input("შენი მეორე საყვარელი ჰობი: ")
hobby3 = input("შენი მესამე საყვარელი ჰობი: ")
print("ჩემი სახელია" + " " + name + " " + surname + " " + "დედაჩემის სახელი და გვარია" + " " + momname + " " + momsurname + " " + "მამაჩემის სახელი და გვარია" + " " + dadname + " " + dadsurname + " " + "ჩემი საყვარელი ფერია" + " " + color + " " + "ჩემი საყვარელი მანქანა არის" + " " + car + " " + "ჩემი ჰობი არის" + " " + hobby1 + " " + hobby2 + " " + hobby3)