birth_year = int(input("შეიტანეთ თქვენი დაბადების წელი: "))
current_year = 2024
print(current_year - birth_year)

height = int(input("შეიტანეთ ოთხკუთხედის სიმაღლე: "))
width = int(input("შეიტანეთ ოთხკუთხედის სიგანე: "))
print(height * width)
print(2 * (height + width))

distance = int(input("შეიტანე შენი სახლიდან სკოლამდე მანძილი კილომეტრებში: "))
print(distance * 1000)
print(distance * 100000)
print(distance * 1000000)

name = input("შენი სახელი: ")
surname = input("შენი გვარი: ")
momname = input("დედის სახელი: ")
momsurname = input("დედის გვარი: ")
dadname = input("მამის სახელი: ")
dadsurname = input("მამის გვარი: ")
color = input("საყვარელი ფერი: ")
car = input("საყვარელი მანქანა: ")
hobby1 = input("შენი პირველი საყვარელი ჰობი: ")
hobby2 = input("შენი მეორე საყვარელი ჰობი: ")
hobby3 = input("შენი მესამე საყვარელი ჰობი: ")
print("ჩემი სახელია" + " " + name + " " + surname + " " + "დედაჩემის სახელი და გვარია" + " " + momname + " " + momsurname + " " + "მამაჩემის სახელი და გვარია" + " " + dadname + " " + dadsurname + " " + "ჩემი საყვარელი ფერია" + " " + color + " " + "ჩემი საყვარელი მანქანა არის" + " " + car + " " + "ჩემი ჰობი არის" + " " + hobby1 + " " + hobby2 + " " + hobby3)