num1 = int(input("შემოიტანე პირველი რიცხვი: "))
num2 = int(input("შემოიტანე მეორე რიცხვი: "))
print(num1 == num2)
print(num1 < num2)
print(num1 > num2)
print(num1 <= num2)
print(num1 >= num2)
print(num1 != num2)